import { DEFAULT_LANGUAGE, type LanguageCode } from "@/lib/cloner/languages"

export type UiCopy = (typeof UI_COPY)[LanguageCode]

export function getUiCopy(language: string): UiCopy {
  return UI_COPY[language as LanguageCode] ?? UI_COPY[DEFAULT_LANGUAGE]
}

export const UI_COPY = {
  pl: {
    language: {
      label: "Język",
      ariaLabel: "Język",
      placeholder: "Język",
    },
    common: {
      next: "Dalej",
      saving: "Zapisywanie...",
      validating: "Sprawdzanie...",
      uploadPhotoError: "Nie udało się zapisać zdjęcia",
      uploadRecordingError: "Nie udało się zapisać nagrania",
      uploadReactionError: "Nie udało się zapisać wideo reakcji",
      uploadRawReactionError: "Nie udało się zapisać kopii reakcji",
    },
    welcome: {
      title: "Cloner",
      lead: "Sklonujemy Cię. Wystarczy jedna prawda o Tobie.",
      description:
        "Nagraj twarz i głos oraz podziel się czymś prawdziwym. W kilka chwil stworzymy Twoją cyfrową wersję AI.",
      cta: "Stwórz moją wersję AI",
      consentPrefix: "Akceptuję ",
      terms: "Regulamin",
    },
    truth: {
      title: "Powiedz nam coś prawdziwego",
      description:
        "Podziel się kilkoma prawdami, czymś ciekawym albo czymś osobistym o sobie.",
      placeholder: "Napisz coś prawdziwego o sobie...",
      minCharacters: "min. znaków",
      examples: [
        "Kiedyś przejechałem pół Europy z bardzo małym budżetem",
        "Boję się motyli, ale prawie nikt o tym nie wie",
        "Nauczyłem się grać na pianinie z filmów w internecie",
      ],
    },
    voice: {
      title: "Przeczytaj to na głos",
      description:
        "Użyjemy Twojego głosu do stworzenia klona AI. Przeczytaj poniższy fragment w wybranym języku.",
      tips: [
        {
          title: "Unikaj hałasu",
          description: "Dźwięki w tle pogarszają jakość nagrania.",
        },
        {
          title: "Sprawdź mikrofon",
          description: "Słuchawki lub zewnętrzny mikrofon zwykle dają lepszy efekt.",
        },
        {
          title: "Używaj tego samego sprzętu",
          description: "Nie zmieniaj mikrofonu między nagraniami.",
        },
      ],
      keepReading: "Czytaj dalej...",
      secondsLeft: "s do końca",
      secondsRequired: "sekund nagrania wymagane",
      recording: "Nagranie:",
      tooShort: "Nagranie jest za krótkie. Nagraj co najmniej",
      seconds: "sekund.",
      reRecord: "Nagraj ponownie",
      creatingVoice: "Tworzenie głosu...",
      stopRecording: "Zatrzymaj nagranie",
      recordingLeft: "Nagrywanie...",
      startRecording: "Rozpocznij nagrywanie",
      micDenied: "Odmowa dostępu do mikrofonu. Zezwól na dostęp do mikrofonu.",
      micUnavailable: "Nie udało się uzyskać dostępu do mikrofonu.",
    },
    photo: {
      title: "Pokaż twarz",
      description: "Ustaw twarz w kadrze i zrób zdjęcie.",
      voiceVerificationTitle: "Weryfikacja głosu",
      voiceVerification:
        "Twoje konto ElevenLabs może wymagać weryfikacji tego klona głosu, zanim będzie można używać go wszędzie. Weryfikację możesz dokończyć w",
      capturedAlt: "Zrobione zdjęcie",
      checkingFace: "Sprawdzanie twarzy...",
      noFace: "Nie wykryto twarzy. Spróbuj lepszego światła albo ustaw się inaczej.",
      loadingFaceDetection: "Ładowanie wykrywania twarzy...",
      retakePhoto: "Zrób zdjęcie ponownie",
      retake: "Powtórz",
      takePhoto: "Zrób zdjęcie",
      cameraDenied:
        "Odmowa dostępu do kamery. Zezwól na dostęp do kamery i spróbuj ponownie.",
      cameraUnavailable: "Nie udało się uzyskać dostępu do kamery. Sprawdź urządzenie.",
    },
    loading: {
      title: "Tworzymy Twojego klona",
      messages: [
        "Analizujemy Twoje cechy...",
        "Klonujemy Twój głos...",
        "Układamy Twoją prawdę...",
        "Renderujemy cyfrowego bliźniaka...",
        "Prawie gotowe...",
      ],
      avatarWaiting: "Wideo avatara jest jeszcze przygotowywane.",
      stillPreparing: "Wciąż przygotowujemy wideo avatara.",
      createFailed: "Nie udało się stworzyć wideo klona.",
      uploadedWaiting: "Wideo avatara zostało przesłane. Czekamy, aż będzie dostępne...",
      notReady: "Wideo klona nie jest jeszcze gotowe.",
      metadataNotReady: "Metadane wideo klona nie są jeszcze gotowe.",
      metadataTimedOut: "Sprawdzanie metadanych wideo klona trwało zbyt długo.",
      notPlayable: "Wideo klona nie jest jeszcze odtwarzalne.",
      notReachable: "Wideo avatara nie jest jeszcze dostępne.",
      notDownloadable: "Wideo avatara nie jest jeszcze możliwe do pobrania.",
      phase: "Etap",
      steps: "Kroki",
    },
    reaction: {
      title: "Twój klon jest gotowy",
      description:
        "Obejrzyj swojego klona AI, a my automatycznie nagramy Twoją reakcję.",
      fallbackDescription: "Podgląd awaryjny jest gotowy do nagrania reakcji.",
      you: "Ty (na żywo)",
      rec: "REC",
      clone: "Twój klon AI",
      noPreview: "Brak podglądu",
      saving: "Zapisywanie nagrania...",
      finalSaved: "Finalny montaż zapisano w",
      rawSaved: "Kopię reakcji zapisano w",
      downloadFallback: "Nadal możesz pobrać nagranie poniżej.",
      download: "Pobierz reakcję",
      startOver: "Zacznij od nowa",
    },
    login: {
      title: "Wpisz hasło projektu",
      description: "Ten proces nagrywania jest prywatny dla projektu artystycznego.",
      password: "Hasło",
      incorrect: "Nieprawidłowe hasło.",
      failed: "Nie udało się zalogować.",
      loading: "Odblokowywanie...",
      submit: "Odblokuj",
    },
    transitions: {
      passwordSuccess: ["Dostęp przyznany."],
      welcomeToTruth: ["Protokół aktywny."],
      truthToVoice: ["Analiza zapisu..."],
      voiceToPhoto: ["Profil głosu zapisany."],
      photoToLoading: ["Inicjalizacja klona..."],
    },
  },
  en: {
    language: {
      label: "Language",
      ariaLabel: "Language",
      placeholder: "Language",
    },
    common: {
      next: "Next",
      saving: "Saving...",
      validating: "Validating...",
      uploadPhotoError: "Could not save photo",
      uploadRecordingError: "Could not save recording",
      uploadReactionError: "Could not save reaction video",
      uploadRawReactionError: "Could not save raw reaction video",
    },
    welcome: {
      title: "Cloner",
      lead: "We're cloning you. One truth about yourself is all it takes.",
      description:
        "Record your face, your voice, and share something real. We'll create a digital AI version of you in seconds.",
      cta: "Create My Digital AI",
      consentPrefix: "I agree to the ",
      terms: "Terms & Conditions",
    },
    truth: {
      title: "Tell us something true",
      description:
        "Share a couple of truths, something interesting, or something intimate about yourself.",
      placeholder: "Write something real about yourself...",
      minCharacters: "min characters",
      examples: [
        "I once hitchhiked across three countries with only $20",
        "I'm terrified of butterflies but nobody knows",
        "I taught myself piano by watching YouTube at 3am",
      ],
    },
    voice: {
      title: "Read this aloud",
      description:
        "We'll use your voice to create your AI clone. Read the passage below in your selected language.",
      tips: [
        {
          title: "Avoid noisy environments",
          description: "Background sounds interfere with recording quality results.",
        },
        {
          title: "Check microphone quality",
          description: "Try external units or headphone mics for better audio capture.",
        },
        {
          title: "Use consistent equipment",
          description: "Don't change recording equipment between samples.",
        },
      ],
      keepReading: "Keep reading...",
      secondsLeft: "s remaining",
      secondsRequired: "seconds of audio required",
      recording: "Recording:",
      tooShort: "Recording too short. Please record at least",
      seconds: "seconds.",
      reRecord: "Re-record",
      creatingVoice: "Creating your voice...",
      stopRecording: "Stop Recording",
      recordingLeft: "Recording...",
      startRecording: "Start Recording",
      micDenied: "Microphone access denied. Please allow microphone access.",
      micUnavailable: "Could not access microphone.",
    },
    photo: {
      title: "Let's see your face",
      description: "Position your face in the frame and take a photo.",
      voiceVerificationTitle: "Voice verification",
      voiceVerification:
        "Your ElevenLabs account may require you to verify this voice clone before it can be used everywhere. You can complete verification in the",
      capturedAlt: "Captured photo",
      checkingFace: "Checking for face...",
      noFace: "No face detected. Try better lighting or reposition yourself.",
      loadingFaceDetection: "Loading face detection...",
      retakePhoto: "Retake Photo",
      retake: "Retake",
      takePhoto: "Take Photo",
      cameraDenied:
        "Camera access denied. Please allow camera access and try again.",
      cameraUnavailable: "Could not access camera. Please check your device.",
    },
    loading: {
      title: "Creating your clone",
      messages: [
        "Analyzing your features...",
        "Cloning your voice...",
        "Crafting your truth...",
        "Rendering your digital twin...",
        "Almost there...",
      ],
      avatarWaiting: "Avatar video is still being prepared.",
      stillPreparing: "Still preparing the avatar video.",
      createFailed: "Could not create clone video.",
      uploadedWaiting: "Avatar video uploaded. Waiting for it to become available...",
      notReady: "Clone video is not ready yet.",
      metadataNotReady: "Clone video metadata is not ready yet.",
      metadataTimedOut: "Clone video metadata check timed out.",
      notPlayable: "Clone video is not playable yet.",
      notReachable: "Avatar video is not reachable yet.",
      notDownloadable: "Avatar video is not downloadable yet.",
      phase: "Phase",
      steps: "Steps",
    },
    reaction: {
      title: "Your Clone is Ready",
      description: "Watch your AI clone and record your reaction!",
      fallbackDescription: "Fallback preview is ready for reaction recording.",
      you: "You (live)",
      rec: "REC",
      clone: "Your AI clone",
      noPreview: "No preview available",
      saving: "Saving recording...",
      finalSaved: "Final composite saved to",
      rawSaved: "Raw reaction backup saved to",
      downloadFallback: "You can still download the recording below.",
      download: "Download reaction",
      startOver: "Start over",
    },
    login: {
      title: "Enter project password",
      description: "This capture flow is private for the art project.",
      password: "Password",
      incorrect: "Incorrect password.",
      failed: "Could not sign in.",
      loading: "Unlocking...",
      submit: "Unlock",
    },
    transitions: {
      passwordSuccess: ["Access granted."],
      welcomeToTruth: ["Protocol active."],
      truthToVoice: ["Processing input..."],
      voiceToPhoto: ["Voice profile archived."],
      photoToLoading: ["Initializing clone..."],
    },
  },
} as const
